# Generated by Django 3.2.12 on 2022-03-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poisson_predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country',
            field=models.CharField(default='Anglia', max_length=32, verbose_name='Kraj'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='Poziom'),
            preserve_default=False,
        ),
    ]
